apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-s3-echoer-with-sa
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 2. How do want to update the pods?
  strategy: 
    type: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: eks-s3-echoer-with-sa

  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: eks-s3-echoer-with-sa
    spec:
      serviceAccountName: s3-echoer
      containers:
      - name: eks-s3-echoer-with-sa
        image: sdscello/awscli:latest
        ports:
        - containerPort: 80
